/********************************************************************
* SiliconDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SiliconDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSiliconDataDict();
extern void G__cpp_setup_inheritanceSiliconDataDict();
extern void G__cpp_setup_typetableSiliconDataDict();
extern void G__cpp_setup_memvarSiliconDataDict();
extern void G__cpp_setup_globalSiliconDataDict();
extern void G__cpp_setup_memfuncSiliconDataDict();
extern void G__cpp_setup_funcSiliconDataDict();
extern void G__set_cpp_environmentSiliconDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SiliconData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SiliconDataDictLN_TClass;
extern G__linked_taginfo G__SiliconDataDictLN_TBuffer;
extern G__linked_taginfo G__SiliconDataDictLN_TMemberInspector;
extern G__linked_taginfo G__SiliconDataDictLN_TObject;
extern G__linked_taginfo G__SiliconDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__SiliconDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SiliconDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SiliconDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SiliconDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SiliconDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SiliconDataDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__SiliconDataDictLN_SiliconData;
extern G__linked_taginfo G__SiliconDataDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__SiliconDataDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
